# Generated by Django 4.2.5 on 2023-10-15 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_lesson_4', '0002_alter_advertisement_id_alter_advertisement_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'verbose_name': 'Объявления', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.RenameField(
            model_name='advertisement',
            old_name='created_up',
            new_name='updated_at',
        ),
    ]
