# Generated by Django 4.2.5 on 2023-10-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lesson_4', '0006_alter_advertisement_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(default='/app_lesson_4/static/img/adv.png', upload_to='advertisements/', verbose_name='изображение'),
        ),
    ]
