# Generated by Django 4.2.5 on 2023-10-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lesson_4', '0010_alter_advertisement_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(null='static/img/adv.png', upload_to='advertisements/', verbose_name='изображение'),
        ),
    ]
