# Generated by Django 4.2.5 on 2023-10-26 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_lesson_4', '0011_alter_advertisement_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='action',
            new_name='auction',
        ),
    ]
