# Generated by Django 4.2.5 on 2023-10-29 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lesson_4', '0012_rename_action_advertisement_auction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='advertisements/', verbose_name='изображение'),
        ),
    ]
